# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71924b37cacc2b9043ba9b5ff777308df1334baed443db9a45a7aa0d521d823f62b6d3f0f665a779a7663af8786a473f6473df8b8b043e4b9cf1fbc09ce90d43

test:
  secret_key_base: e920f02a5048276123e33d02cf70ffdc26bb7cbde689ea6ea81282a46c1de915e43be97df37f93beeab7c3a63d0254e6df896164574cb701bfff59138a1983f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
